### ISSUE TITLE
Problem with using the jira/notify when your name is not set in circle ci

### ISSUE THREAD

**Issue by mauriciojovel** [CircleCI-Public/jira-connect-orb#40]
### Orb version
1.1.4

### What happened

When you execute the the jira/notify this execute the following line to verify if your token is valid

```
verify_api_key () {
  URL="https://circleci.com/api/v2/me"
  fetch $URL /tmp/me.json
  jq -e '.name' /tmp/me.json
}
```
The problem is for some weird reason my name is not set in the circle ci returning the following output
(example api response)
{
  "name": null,
  "login": "my_login_name",
  "id": "a numeric id"
}

```
200:https://circleci.com/api/v2/me
null

Exited with code exit status 1
```

### Expected behavior

You need change the look up field for the field `login` to verify the information.

**Comment by KyleTryon** [comment]
@mauriciojovel Fixing this right now. I am shocked this was somehow not captured in testing. Can you tell me if you ran into a hard error (where the command actually exits at this point), or did the job continue to run but you were able to see this is where it failed?

Passing the token to the endpoint should resolve this, testing it now.

**Comment by KyleTryon** [comment]
Hello @mauriciojovel,

Could you please let us know if you are still experiencing this issue in version 1.1.6?

**Comment by mauriciojovel** [comment]
Hi @KyleTryon,

The problem still in the version 1.1.6

<img width="928" alt="Screenshot 2020-04-08 09 32 39" src="https://user-images.githubusercontent.com/4094038/78803276-07ae7200-797c-11ea-95f4-6b60952e0b7b.png">

**Comment by KyleTryon** [comment]
Hello @mauriciojovel,

We believe the issue may be that a personal access token is not being used: https://github.com/CircleCI-Public/jira-connect-orb/issues/39

could you please verify with a new personal access token that this is still an issue? (not a project token)

**Comment by if-igor** [comment]
Hi @KyleTryon 

I am seeing the exact same issue. I am using a personal token, but my "name" is showing null as well for some reason. I am assuming the name comes from BitBucket, and it's set there, but CircleCi doesn't pick up on it.

I think changing the check from `jq -e '.name' /tmp/me.json` to `jq -e '.login' /tmp/me.json` would fix this issue, as the login is there for all users.

**Comment by KyleTryon** [comment]
https://circleci.com/orbs/registry/orb/circleci/jira 1.1.7 released. Thank you @mauriciojovel . Thank you for confirmation @if-igor, I was able to double-confirm that. 

https://github.com/CircleCI-Public/jira-connect-orb/pull/41 is merged.
